%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

Name:           ros-jazzy-ffw-teleop
Version:        1.1.10
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ffw_teleop package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       python%{python3_pkgversion}-tkinter
Requires:       ros-jazzy-rclpy
Requires:       ros-jazzy-ros-workspace
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  python%{python3_pkgversion}-tkinter
BuildRequires:  ros-jazzy-rclpy
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
FFW teleop ROS 2 package.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/jazzy"

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Thu Aug 14 2025 Pyo <pyo@robotis.com> - 1.1.10-1
- Autogenerated by Bloom

* Fri Jul 18 2025 Pyo <pyo@robotis.com> - 1.1.9-1
- Autogenerated by Bloom

* Tue Jul 15 2025 Pyo <pyo@robotis.com> - 1.1.8-1
- Autogenerated by Bloom

* Fri Jul 11 2025 Pyo <pyo@robotis.com> - 1.1.7-1
- Autogenerated by Bloom

* Mon Jul 07 2025 Pyo <pyo@robotis.com> - 1.1.6-1
- Autogenerated by Bloom

* Mon Jun 30 2025 Pyo <pyo@robotis.com> - 1.1.5-1
- Autogenerated by Bloom

* Mon Jun 30 2025 Pyo <pyo@robotis.com> - 1.1.4-1
- Autogenerated by Bloom

* Mon Jun 09 2025 Pyo <pyo@robotis.com> - 1.0.9-1
- Autogenerated by Bloom

* Wed Jun 04 2025 Pyo <pyo@robotis.com> - 1.0.8-1
- Autogenerated by Bloom

* Fri May 09 2025 Pyo <pyo@robotis.com> - 1.0.5-1
- Autogenerated by Bloom

