# Default initial positions for ffw's ros2_control fake system

initial_positions:
  arm_l_joint1: 0
  arm_l_joint2: 0
  arm_l_joint3: 0
  arm_l_joint4: 0
  arm_l_joint5: 0
  arm_l_joint6: 0
  arm_l_joint7: 0
  arm_r_joint1: 0
  arm_r_joint2: 0
  arm_r_joint3: 0
  arm_r_joint4: 0
  arm_r_joint5: 0
  arm_r_joint6: 0
  arm_r_joint7: 0
  linear_joint: 0
  neck_joint1: 0
  neck_joint2: 0
