services:
  novnc-server:
    container_name: novnc-server
    image: robotis/novnc-server:latest
    restart: "no"
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-30}
      - DISPLAY=:99
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - WEBSOCKIFY_PORT=8090
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
    privileged: true
