services:
  ai_worker:
    container_name: ai_worker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WITH_GAZEBO=${WITH_GAZEBO:-true}
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../:/root/ros2_ws/src/ai_worker/
      - ./lerobot/outputs:/root/ros2_ws/src/physical_ai_tools/lerobot/outputs
      - ./huggingface:/root/.cache/huggingface
    privileged: true
    command: bash
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
