controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 100  # Hz

    arm_l_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_r_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    neck_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    body_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_l_controller:
  ros__parameters:
    joints:
      - arm_l_joint1
      - arm_l_joint2
      - arm_l_joint3
      - arm_l_joint4
      - arm_l_joint5
      - arm_l_joint6
      - arm_l_joint7
      - l_rh_r1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

arm_r_controller:
  ros__parameters:
    joints:
      - arm_r_joint1
      - arm_r_joint2
      - arm_r_joint3
      - arm_r_joint4
      - arm_r_joint5
      - arm_r_joint6
      - arm_r_joint7
      - r_rh_r1_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

neck_controller:
  ros__parameters:
    joints:
      - neck_joint1
      - neck_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true

body_controller:
  ros__parameters:
    joints:
      - linear_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
